version: '3.8'

services:
  # PostgreSQL database - Primary database for PostgREST and RLS
  postgres:
    image: postgres:16-alpine
    container_name: kickstack-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kick
      POSTGRES_PASSWORD: kickpass
      POSTGRES_DB: kickstack
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kick -d kickstack"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kickstack-network

  # PostgREST - Auto-generate REST API from database schema
  postgrest:
    image: postgrest/postgrest:v12.0.2
    container_name: kickstack-postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://kick:kickpass@postgres:5432/kickstack"
      PGRST_DB_SCHEMAS: "public"
      PGRST_DB_ANON_ROLE: "anon"
      PGRST_JWT_SECRET: "${JWT_SECRET}"
      PGRST_JWT_AUD: "authenticated"
      PGRST_SERVER_CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kickstack-network

  # GoTrue - Authentication service with JWT
  gotrue:
    image: supabase/gotrue:v2.151.0
    container_name: kickstack-gotrue
    ports:
      - "9999:9999"
    environment:
      GOTRUE_API_HOST: "0.0.0.0"
      GOTRUE_API_PORT: "9999"
      GOTRUE_DB_DRIVER: "postgres"
      GOTRUE_DB_DATABASE_URL: "postgres://kick:kickpass@postgres:5432/kickstack?sslmode=disable"
      GOTRUE_SITE_URL: "http://localhost:3001"
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_ADMIN_ROLES: "service_role"
      GOTRUE_JWT_AUD: "authenticated"
      GOTRUE_JWT_DEFAULT_GROUP_NAME: "authenticated"
      GOTRUE_JWT_EXP: "3600"
      GOTRUE_JWT_SECRET: "${JWT_SECRET}"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_SMTP_HOST: "mailhog"
      GOTRUE_SMTP_PORT: "1025"
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_ADMIN_EMAIL: "admin@kickstack.local"
      GOTRUE_MAILER_URLPATHS_INVITE: "/auth/v1/verify"
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: "/auth/v1/verify"
      GOTRUE_MAILER_URLPATHS_RECOVERY: "/auth/v1/verify"
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "/auth/v1/verify"
      GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
      GOTRUE_SMS_AUTOCONFIRM: "false"
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - kickstack-network

  # MinIO - S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: kickstack-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - kickstack-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MailHog - Email testing server for local development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: kickstack-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - kickstack-network

volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local

networks:
  kickstack-network:
    driver: bridge